"""Search-discovery documents generated by Pagecraft."""
from __future__ import annotations

from datetime import datetime, timezone
from xml.etree.ElementTree import Element, SubElement, tostring


def _iso_date(value: datetime | None) -> str:
    value = value or datetime.now(timezone.utc)
    return value.date().isoformat()


def build_sitemap(entries: list[dict]) -> str:
    """Build a deterministic XML sitemap from absolute URL entries."""
    root = Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    for entry in entries:
        node = SubElement(root, "url")
        SubElement(node, "loc").text = entry["url"]
        SubElement(node, "lastmod").text = _iso_date(entry.get("lastmod"))
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + tostring(root, encoding="unicode").replace(" />", "/>")


def build_robots(site_config) -> str:
    """Build a conservative robots file that points crawlers to the sitemap."""
    lines = ["User-agent: *", "Allow: /"]
    if site_config.sitemap_enabled and not site_config.is_placeholder_url:
        lines.extend(["", f"Sitemap: {site_config.sitemap_url}"])
    return "\n".join(lines) + "\n"
